In [10]:
# A)
import numpy as np

# i)
arr1D=np.array([2,4,1,0,1,2,2,6],dtype=int)
print("i) 1D array having 8 elements:\n")
print(arr1D)

# ii)
arr2D=np.random.randint(10,size=(4,3))
print("\n\nii)2D array having 4 rows and 3 columns elements:\n")
print(arr2D)

# iii)
arr3D=np.random.randint(10,size=(4,2,3))
print("\n\niii)3D array having the shape 4x2x3:\n")
print(arr3D)

# iv)
arr4D=np.random.randint(10,size=(1,4,2,3))
print("\n\niv)4D array having the shape 1x4x2x3:\n")
print(arr4D)

i) 1D array having 8 elements:

[2 4 1 0 1 2 2 6]


ii)2D array having 4 rows and 3 columns elements:

[[7 1 6]
 [3 4 8]
 [8 0 0]
 [5 7 3]]


iii)3D array having the shape 4x2x3:

[[[6 0 5]
  [5 4 3]]

 [[6 6 9]
  [8 8 0]]

 [[9 2 3]
  [3 1 6]]

 [[1 6 0]
  [1 1 2]]]


iv)4D array having the shape 1x4x2x3:

[[[[8 2 9]
   [7 2 1]]

  [[4 8 6]
   [2 2 6]]

  [[4 3 0]
   [1 5 3]]

  [[6 6 5]
   [0 8 3]]]]


In [21]:
# B)
import sympy as sp
x=sp.Symbol('x')

# i)
f1=2*x*(x-3)*(sp.sin(x)-5)
df_f1=sp.diff(f1,x)
int_f1=sp.integrate(f1,x)
print("i)\nDifferentiation of f1(x):")
sp.pprint(df_f1)
print("\nIntegral of f1(x):")
sp.pprint(int_f1)

# ii)
f2=3*x**3-6*sp.sqrt(x)+3*x
df_f2=sp.diff(f2,x)
int_f2=sp.integrate(f2,x)
print("\n\nii)\nDifferentiation of f2(x):")
sp.pprint(df_f2)
print("\nIntegral of f2(x):")
sp.pprint(int_f2)

i)
Differentiation of f1(x):
2⋅x⋅(x - 3)⋅cos(x) + 2⋅x⋅(sin(x) - 5) + 2⋅(x - 3)⋅(sin(x) - 5)

Integral of f1(x):
      3                                                                      
  10⋅x       2              2                                                
- ───── - 2⋅x ⋅cos(x) + 15⋅x  + 4⋅x⋅sin(x) + 6⋅x⋅cos(x) - 6⋅sin(x) + 4⋅cos(x)
    3                                                                        


ii)
Differentiation of f2(x):
   2       3 
9⋅x  + 3 - ──
           √x

Integral of f2(x):
              4      2
     3/2   3⋅x    3⋅x 
- 4⋅x    + ──── + ────
            4      2  
